added menu to header, fixes #5
njosieb/pjm-contracting-home pull request #13
Opened 2017-03-02 02:03 UTC by njosieb

Added menu to header of page. @cvharris

2017-03-04 17:17 UTC, cvharris requested changes

2017-03-04 17:17 UTC, cvharris commented on src/_layouts/header.njk
> +    </div>
We could actually make use of Nunjuck's built-in [for-loop](https://mozilla.github.io/nunjucks/templating.html#for) to make this a lot more simple, so we can make use of everything in the `menu.yml`

2017-03-04 17:17 UTC, cvharris commented on src/_layouts/header.njk
> +        <a title="Residential" href="/#residential"></a>
this should ultimately look like `<a title="{$ link.description $}" href="{$ link.route $}" class="menu-item">{$ link.label $}</a>`

2017-03-11 18:00 UTC, njosieb commented
@cvharris  Please look at adjustments I made to make sure it works like it should.

2017-03-11 18:14 UTC, cvharris approved these changes
Awesome! 👍 Merge this!

2017-03-11 18:31 UTC, merged