added parallax to background
njosieb/pjm-contracting-home pull request #14
Opened 2017-03-03 00:51 UTC by njosieb

Fixes card #6 @cvharris

2017-03-04 17:18 UTC, cvharris requested changes
Let's wait until #13 merges before we merge this one.

2017-03-11 19:33 UTC, njosieb commented
I merged conflicts with the master. @cvharris

2017-03-11 19:36 UTC, cvharris requested changes

2017-03-11 19:36 UTC, cvharris commented on src/_styles/shared/layout.less
> +    background-image: url(denver-kitchen-remodel.jpg);
If another element were to have the class `.parallax-image` it'll also have to get this `background-image`. We should only apply this specific `background-image` to an id target of some sort, possibly `#top-splash`

2017-03-11 20:15 UTC, njosieb commented
Fixed parallax problems on the background image. @cvharris

2017-03-11 20:54 UTC, njosieb commented
Made sure background image was in the right place. @cvharris

2017-03-11 21:03 UTC, cvharris approved these changes
Looks good! Great job! 👍 🥇 💯

2017-03-14 00:43 UTC, merged